const LANGUAGES = [
    { language: "Arabic", languageCode: "ar"},
    { language: "Bangla", languageCode: "bn"},
    // { language: "Chinese Mandarin", languageCode: "zh-Hans"},
    { language: "Czech", languageCode: "cs"},
    { language: "Danish", languageCode: "da"},
    { language: "Dutch", languageCode: "nl"},
    { language: "English", languageCode: "en"},
    { language: "Filipino", languageCode: "fil"},
    { language: "Finnish", languageCode: "fi"},
    { language: "French", languageCode: "fr"},
    { language: "German", languageCode: "de"},
    { language: "Greek", languageCode: "el"},
    { language: "Gujarati", languageCode: "gu"},
    { language: "Hindi", languageCode: "hi"},
    { language: "Hungarian", languageCode: "hu"},
    { language: "Indonesian", languageCode: "id"},
    { language: "Italian", languageCode: "it"},
    { language: "Japanese", languageCode: "ja"},
    { language: "Kannada", languageCode: "kn"},
    { language: "Korean", languageCode: "ko"},
    { language: "Malayalam", languageCode: "ml"},
    { language: "Norwegian", languageCode: "nb"},
    { language: "Polish", languageCode: "pl"},
    // { language: "Portuguese (Portugal)", languageCode: "pl"},
    { language: "Russian", languageCode: "ru"},
    { language: "Slovak", languageCode: "sk"},
    { language: "Spanish", languageCode: "es"},
    { language: "Swedish", languageCode: "sv"},
    { language: "Tamil", languageCode: "ta"},
    { language: "Telugu", languageCode: "te"},
    { language: "Thai", languageCode: "th"},
    { language: "Turkish", languageCode: "tr"},
    { language: "Ukranian", languageCode: "uk"},
    { language: "Vietnamese", languageCode: "vi"}
];

export default LANGUAGES;